### ISSUE TITLE
Minification of my project using webpack causes angular exceptions

### ISSUE THREAD

**Issue by antoniomercado** [720kb/angular-tooltips#138]
In my entry point to my application, when I require the module name as such...

`require('angular-tooltips')`

Minification causes my staging deployment to break with an error `unknown provider tooltipsDirective`

I have to change my require to use the distribution minified version supplied with the module download as such...

`require('../node_modules/angular-tooltips/dist/angular-tooltips.min')`

**Comment by wouldgo** [comment]
The main in package.json is pointing anything valid right now.
I'm preparing the patched version right now.

**Comment by antoniomercado** [comment]
Awesome!! I appreciate that. Waiting for the patch :+1:

**Comment by wouldgo** [comment]
Done, also published in npm registry as version 1.0.7, let me know what happens :smile:.

**Comment by antoniomercado** [comment]
Unfortunately that didn't fix the issue :disappointed:

I'll look deeper into this when I have a free moment and possibly offer up a patch unless you get to it first.

**Comment by wouldgo** [comment]
As far as I can see (I'm not a webpack user at all) you should do something like this:
```js
let tooltips = require('angular-tooltips');

angular.module('myModule', [tooltips]);

```

Is this working?

**Comment by phillipj** [comment]
Confirming it works with webpack and v1.0.7 when using as you just described @wouldgo ^^
