### ISSUE TITLE
Tooltips are always set to  visibility: visible causing conflicts with Protractor

### ISSUE THREAD

**Issue by cs-NET** [720kb/angular-tooltips#94]
The tooltips are shown and hidden with transitions however the visibility remains set to visible. This results in Protoractor detecting the tooltips on top of elements you may be trying to test causing the tests to fail.

Possible workaround is to set visibility to hidden on hideTooltip and back to visible on showTooltip?

**Comment by 45kb** [comment]
Hi @cs-NET  try updating the module version i just released something that could fix your problem.

If not enough consider altering the angular-tooltips.css file, you have two classes:

```css
/*tooltip hidden (default class)*/
._720kb-tooltip {
}
```

```css
/*tooltip is shown (as soon as tooltipShow is called this class is pushed to the tooltip)*/
._720kb-tooltip._720kb-tooltip-open {
  visibility: '';
  opacity: 1;
}
```

Let know if you try, thank you.

**Comment by cs-NET** [comment]
Thanks @45kb for looking at this, I have tested the update and the issue still exists. Based on your suggestion above I came up with the following work around for now:

```css
._720kb-tooltip {
    visibility: hidden !important;
}

._720kb-tooltip._720kb-tooltip-open {
    visibility: visible !important;
}
```

Looking at the code I notice that the visibility: visible is set on the style so I had to add !important to the css. It looks like it is being used as a way to manage the isTooltipEmpty() state. My work around will result in an empty tooltip being shown on a hover? Therefore will likely break some use cases.

```javascript
$scope.initTooltip = function initTooltip(tooltipSide) {
          if (!$scope.isTooltipEmpty()) {

            theTooltip.css('visibility', 'visible');

            height = thisElement[0].offsetHeight;
            width = thisElement[0].offsetWidth;

            //get tooltip dimension
            theTooltipHeight = theTooltip[0].offsetHeight;
            theTooltipWidth = theTooltip[0].offsetWidth;

            $scope.parseSpeed();
            $scope.tooltipPositioning(tooltipSide);
          } else {
            theTooltip.css('visibility', 'hidden');
          }
        };
```

**Comment by 45kb** [comment]
@cs-NET as soon as i got some time to focus on this i will try removing ```theTooltip.css('visibility', 'visible');``` which, actually, looks really no more needed :+1:

**Comment by erapoport** [comment]
I'm also having an issue where about 3rd of the screen is not clickable because there used to be a big tooltip there. The `!important` fix works for me in the meantime.
